@token    = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3YmU1ZTUwOC0wNWVlLTRmOTYtYmNhMS00NmY3ZDFjNjE5MDciLCJleHAiOjE3ODE4OTM3OTh9.qJGSAh-rB1qcDOqtoRpnkMDoKOcoWX4UfLdVAD4pwcM
@order_id = 00000000-0000-0000-0000-000000000000

### create (public)
POST {{base}}/orders
Content-Type: application/json

{
    "customer_email": "cliente@ejemplo.com",
    "customer_name":  "Juan Pérez",
    "customer_phone": "+5492291234567",
    "items": [
        { "product_id": "da9c448a-c2d0-4b9b-be03-9ede5ab822d6", "quantity": 500 },
        { "product_id": "0d80f1eb-3a8f-4592-a0f8-b279a4856b91", "quantity": 2 }
    ]
}

### get_all (admin)
@page     = 1
@per_page = 25
GET {{base}}/orders?page={{page}}&per_page={{per_page}}
Authorization: Bearer {{token}}

### get_by_id (public)
GET {{base}}/orders/{{order_id}}
