### create
POST {{base}}/products
Content-Type: application/json

{
    "description":         "A test product",
    "image_url":           null,
    "low_stock_threshold": 5,
    "name":                "Test Product",
    "price_cents":         1999,
    "stock":               20,
    "symbols":             ["vegan"],
    "unit_of_measure":     "kg"
}

### get_all
@page = 1
@per_page = 50
GET {{base}}/products?page={{page}}&per_page={{per_page}}

### get_by_id
@product_id = df412cc0-10cb-4bc5-84ab-016602851a6c
GET {{base}}/products/{{product_id}}
