@product_id = 679986fa-0758-4696-af14-738f0191ae01
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxZGI5MGI0YS1iZDA4LTRhZWQtYTQxNS1lMmJjMmU2OGM5MDMiLCJleHAiOjE3Nzg1MDg3NzV9.8K0N0QGZkLj6cFqP4Xvo92Lv_6DZcWl0_LhMI7JQ4vI

### create
POST {{base}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "description":         "A test product",
    "image_url":           null,
    "low_stock_threshold": 5,
    "name":                "Test Product",
    "price_cents":         1999,
    "stock":               20,
    "symbols":             ["vegan"],
    "unit_of_measure":     "kg"
}

### get_all
@page = 1
@per_page = 50
GET {{base}}/products?page={{page}}&per_page={{per_page}}

### get_by_id
GET {{base}}/products/{{product_id}}

### update
PATCH {{base}}/products/{{product_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "description":         "new description",
    "image_url":           null,
    "low_stock_threshold": 5,
    "name":                "new name",
    "price_cents":         1999,
    "stock":               20,
    "symbols":             ["vegan"],
    "unit_of_measure":     "kg"
}
