@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyYjVmMmI4MS04OTg3LTQzNDktOThiMS05ZDkzMGVmNTlkYzgiLCJleHAiOjE3NzgxNTc5NDJ9.Gi5cBfv6Shwds2EiaIlPw8w7ESK-DrSaR-BIm7dppgA
@user_id = 2b5f2b81-8987-4349-98b1-9d930ef59dc8

### create
POST {{base}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email":    "test_0@example.com",
    "password": "secret123456789"
}

### get_all
@page = 1
@per_page = 10
GET {{base}}/users?page={{page}}&per_page={{per_page}}
Authorization: Bearer {{token}}

### get_by_id
GET {{base}}/users/{{user_id}}
Authorization: Bearer {{token}}

### update
PATCH {{base}}/users/{{user_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "test_update@example.com"
}

### update_password
PATCH {{base}}/users/{{user_id}}/password
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password": "new_password12345"
}
