server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    location ~ ^/(auth|products) {
        proxy_pass         http://host.docker.internal:3000;
        proxy_http_version 1.1;
    }
}
